
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-api-v2
  namespace: {{ .Release.Namespace }}
  labels:
    app: open-api
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-api
      version: v2
  template:
    metadata:
      labels:
        app: open-api
        version: v2
    spec:
      containers:
      - name: open-api
        image: {{.Values.image.imageRegistry}}/cs-open-api-v1:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: Hosts__BasePath
          value: "/open-api"
        ports:
        - containerPort: 5012
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
