apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - {{ .Values.hosts.web }}
  gateways:
  - cs-gateway
  http:
  # uncomment for fault injection
  # - fault:
  #     # delay: 
  #     #   fixedDelay: 5s
  #     #   percent: 100
  #     abort:
  #       httpStatus: 500
  #       percent: 100
  #   match:
  #   - headers:
  #       x-username:
  #         exact: thang
  #     uri:
  #       prefix: /catalog
  #   route:
  #   - destination:
  #       host: open-api
  #       subset: v1
  #       port:
  #         number: 80
  #     weight: 100

  - match:
    - uri:
        prefix: /catalog/
    - uri:
        prefix: /catalog
    rewrite:
      uri: /catalog/
      authority: {{ .Values.hosts.api }}
    route:
    - destination:
        host: open-api
        subset: v1
        port:
          number: 80
      weight: 100
    # uncomment when apply shadow - mirroring
    # mirror:
    #   host: open-api
    #   subset: v2
    #   port:
    #       number: 80
    # uncomment when apply canary
    # - destination:
    #     host: open-api
    #     subset: v2
    #     port:
    #       number: 80
    #   weight: 30

  - match:
    - uri:
        prefix: /cart/
    - uri:
        prefix: /cart
    rewrite:
      uri: /cart/
      authority: {{ .Values.hosts.api }}
    route:
    - destination:
        host: open-api
        subset: v1
        port:
          number: 80
      weight: 100
  - match:
    - uri:
        prefix: /inventory/
    - uri:
        prefix: /inventory
    rewrite:
      uri: /inventory/
      authority: {{ .Values.hosts.api }}
    route:
    - destination:
        host: open-api
        subset: v1
        port:
          number: 80
      weight: 100
  # - match:
  #   - uri:
  #       prefix: /rating/
  #   - uri:
  #       prefix: /rating
  #   rewrite:
  #     uri: /rating/
  #     authority: {{ .Values.hosts.api }}
  #   route:
  #   - destination:
  #       host: open-api
  #       subset: v1
  #       port:
  #         number: 80
  #     weight: 100
  - match:
    - uri:
        prefix: /open-api/
    - uri:
        prefix: /open-api
    rewrite:
      uri: /open-api/
      authority: {{ .Values.hosts.api }}
    route:
    - destination:
        host: open-api
        subset: v1
        port:
          number: 80
      weight: 100

  - match:
    - uri:
        prefix: /config/
    - uri:
        prefix: /config
    rewrite:
      uri: /
      authority: {{ .Values.hosts.idp }}
    route:
    - destination:
        host: idp
        port:
          number: 80
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spa
        port:
          number: 80
---

# uncomment when apply shodow - mirroring
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: open-api-destination-rule
spec:
  host: open-api
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
