apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "coolstore-jwt-authentication"
spec:
  targets:
  - name: open-api  
  origins:
  - jwt:
      issuer: "http://id.cool-store.ml"
      jwksUri: "http://id.cool-store.ml/.well-known/openid-configuration/jwks"
      # trigger_rules:
      # - excluded_paths:
      #   - exact: /open-api/catalog/api/products/ping
  principalBinding: USE_ORIGIN